### ISSUE TITLE
Sandbox Error Message: cannot find module...

### ISSUE THREAD

**Issue by mindlessha** [tomtheisen/mutraction#5]
When clicking "Try it" from the Events page (Topics - Events), the sandbox text editor shows a red underline on line 1. Hovering over it reads: cannot find module 'mutraction-dom/jsx-runtime' or its corresponding type declarations.(2307)

The program does seem to work - if I click "Click" I get a popup with "mutraction.dev says Hello"
![SandboxError_2307_cannotfindmodule](https://github.com/tomtheisen/mutraction/assets/143980749/08bc2e33-206b-47a8-a76f-7bddb3cd5acf)

**Comment by tomtheisen** [comment]
In order to get JSX types resolution, the code in the editor has to be considered a "module".  Normally, that means there's an explicit `import` or `export`.   In fact `export {}` works.

As you note, this is purely an editor-displayed error.  The function of the sandbox script is unaffected.

However, there shouldn't be an error by default.  Maybe I can find a way to force the file into "module" status without an import/export.  If not, I'll ensure there's at least a blank import/export for all the standard example links.

**Comment by tomtheisen** [comment]
Resolved in cecab3cb8729e36c58a61ab02656001cfab5f283
