### ISSUE TITLE
Allow element attribute `class`

### ISSUE THREAD

**Issue by naturalethic** [tomtheisen/mutraction#9]
Currently only `className` is supported.

**Comment by tomtheisen** [comment]
Currently all the jsx properties translate to properties of DOM objects, rather than HTML attributes.  Hence `className`, and `innerHTML`.  But it probably makes sense to support some well-known html attributes in addition.  This is easy to do, and I don't see much reason not to.

Can you think of any other than `class`?

**Comment by naturalethic** [comment]
Can't think of any others offhand.

**Comment by tomtheisen** [comment]
I made the change in df8f99c.  I didn't make any documentation changes.  I haven't published the npm package or sandbox, but it will be in the next release/publish.
